# services:
#   - type: web
#     name: your-app-name
#     env: php
#     buildCommand: composer install --no-dev --optimize-autoloader && php artisan config:cache && php artisan route:cache && php artisan view:cache && npm install && npm run build
#     startCommand: php artisan serve --host 0.0.0.0 --port $PORT
#     envVars:
#       - key: APP_NAME
#         value: Laravel
#       - key: APP_ENV
#         value: production
#       - key: APP_DEBUG
#         value: false

services:
  - type: web
    name: your-app-name
    env: php

    buildCommand: |
      # Ensure PHP is installed
      curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
      apt-get install -y nodejs

      # Install Composer dependencies
      composer install --no-dev --optimize-autoloader

      # Cache configurations for better performance
      php artisan config:cache
      php artisan route:cache
      php artisan view:cache

      # Install and build frontend assets (if applicable)
      npm install
      npm run build
    startCommand: php artisan serve --host 0.0.0.0 --port $PORT
    envVars:
      - key: APP_NAME
        value: Laravel
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: 'pgsql'  # Change to 'pgsql' if using PostgreSQL
      - key: DB_HOST
        sync: false  # Set database host manually in Render dashboard
      - key: DB_PORT
        value: 5432  # Use 5432 for PostgreSQL
      - key: DB_DATABASE
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
